//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КУРСОВАЯ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int КодКлиента { get; set; }
        public int КодМаршрута { get; set; }
        public int КодВодителя { get; set; }
        public int КодТС { get; set; }
        public int КодЗаказа { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime Дата { get; set; }
        public System.DateTime ДатаОкончания { get; set; }
    
        public virtual Водитель Водитель { get; set; }
        public virtual Маршрут Маршрут { get; set; }
        public virtual ТС ТС { get; set; }
        public virtual Клиент Клиент { get; set; }
    }
}
