//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КУРСОВАЯ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class МодельПрицепа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public МодельПрицепа()
        {
            this.Прицеп = new HashSet<Прицеп>();
        }
    
        public int КодМоделиПрицепа { get; set; }
        public double Объем { get; set; }
        public double Грузоподъемность { get; set; }
        public string Модель { get; set; }
        public string Марка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Прицеп> Прицеп { get; set; }
    }
}
