//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КУРСОВАЯ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прицеп
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Прицеп()
        {
            this.ТС = new HashSet<ТС>();
        }
    
        public string Госномер { get; set; }
        public int КодПрицепа { get; set; }
        public int КодМоделиПрицепа { get; set; }
    
        public virtual МодельПрицепа МодельПрицепа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТС> ТС { get; set; }
    }
}
